### ISSUE TITLE
PoM - Unlock SIM

### ISSUE THREAD

**Issue by kimhansen** [Kwamecorp/Fairphone#1]
When the PoM is finished, the phone doesn't resume: it stays idle, waiting for the user to insert the SIM card code (when users have this setting on, which most of them have).

**Comment by sevan6** [comment]
Maybe not linked to PoM directly:
I have noticed that when you switch to Flight Mode on (disconnection) and off again (reconnection), the PIN code is asked.
So it is probably directly linked to the Flight Mode management, not PoM itself.

Sevan

**Comment by jonnius** [comment]
It would already help if there was a notification at the end of "peace", so that the one not forgets to reactivate SIM, not beeing reachable.
