### ISSUE TITLE
[PeaceOfMind]Help button not visible on screen

### ISSUE THREAD

**Issue by dalb8** [Kwamecorp/Fairphone#12]
I ran the app on a normal sized hdpi phone and when I launch the main activity the "?" isn't visible, only the slider.

**Comment by pinkpawkitty** [comment]
You might want to try this: https://github.com/mudar/Fairphone (it's a fork creating an app for the play store, the stuff in this repo seems to be optimized for the FP1)

**Comment by dalb8** [comment]
Fair enough ;-) That's much better and (s)he's talking about adapting the launcher too, so I'll be direct my whingeing there.
