### ISSUE TITLE
alarm loudness level 1 is actually silent

### ISSUE THREAD

**Issue by Cathryne** [Kwamecorp/Fairphone#27]
On FairphoneOS 1.1, the alarm's loudness level 0 is mute as it should be, but 1 is absolutely silent as well. 2 is a lot louder than I was used to from another Android phone at level 1. All other loudness levels (speaker, ring etc.) seem to be correctly mute only at 0 and reasonably quiet at 1.

**Comment by keesj** [comment]
Hi,

This issue was fixes in 1.6 sorry for the late reply

**Comment by Cathryne** [comment]
OK, thanks :-) However, please improve the [availability of change logs](https://fairphone.zendesk.com/hc/communities/public/questions/201915917-Fairphone-1-1-change-log). Also old ones. Your blog would be a good place, or [this forum section](https://fairphone.zendesk.com/hc/en-us/sections/200427307-Resources).
