### ISSUE TITLE
Redundant files for translations?

### ISSUE THREAD

**Issue by ccamara** [Kwamecorp/Fairphone#6]
I'm copying some comments that arised in #4 that were not related to Catalan translations only but to translations in general and file structure.

I've noticed some inconsistencies in the number of files available per language: some of them have a single file called `strings.xml` whereas others have another one called `styles.xml`

As @javiercoll noticed " in those cases, the app will pick the default xml files, which can be found at 'values' or 'layout' folders (let's say, the folders without language extension)"

However if you take further detail you'll see that `layout` folder's files do not have any string to be translated. Additionally it doesn't explain why does some languages have a `styles.xml` file inside which has exactly the same content each other. To make things worse, this content is also present in `layout/styles.xml` (Although it has much more content). All of these makes me think that:
1. `styles.xml` per language basis should be removed, since they have redundant information, in favour of more general file at `layout/styles.xml`.
2. `values-xx/styles.xml` should be removed, since they do not provide any per-language information and they are redundant.

If I am right in any of those assumptions I would be glad to do it in another branch/pull request, so I'll wait for @kimhansen's confirmation

Cheers

**Comment by ccamara** [comment]
Copying @javiercoll's answer:

> The fastest way to check that is to remove the files and check it on the android emulator. If it doesn't explode, that's it. Althought, if you create a branch only for that and @kimhansen doesn't feel right about it, he just has to discard it.

I don't have any experience on Android development/debugging. Could you explain me how to do that so I can try it myself and learn as well? If it's not too much work it would be nice to have such instructions in this [repo's wiki](https://github.com/Kwamecorp/Fairphone/wiki) 

Thanks!

**Comment by javiercoll** [comment]
Hi @ccamara,

Depending on which knowledge you already have, I'll list you the things you need:
- Android Development Kit (which include eclipse and androir libraries)
- Your code downloaded from Github
- An android emulator configured

Let me know what you already have installed/configured, and I'll send you tutorials about them

**Comment by ccamara** [comment]
Thank you @javiercoll! 
To be honest, my knowledge about Android Apps is below zero, but I love learning! I don't have any Android Development Kit. I'm an architect converted to drupal wedvelopment so I have some knowledge about php, css, drupal... I usually work with Linux (Kubuntu) and although I used to install eclipse I don't use it anymore in favour of sublime or Kdevelop.

**Comment by javiercoll** [comment]
Nice, nice, that's the spirit!

In that case, you should take a look at Java development, as it's the android basis. But to be honest, my Java skills are 0, I'm focused more on JavaScript; and for translations we don't need them, so it's ok!

To start with, you should take a look at how to install the ADK. Here you can find the Google tutorials. You can find information about the emulators too:

http://developer.android.com/sdk/installing/index.html

And about downloading the code, if you don't know how to use Git, you can do two things:
- Download GitHub application (I'm not sure if it exists for linux)
- Create a zip of your project and download it (there is a button on the right sidebar on your project page)

I'm sorry I can't help you more, but as said, I'm learning Android (and git/github!) with this project too

Let me know how you're doing!

**Comment by ccamara** [comment]
Thanks for the links. I'll try some of those resources I'll give a try to Android SDK and [Android Studio](http://developer.android.com/sdk/installing/studio.html). As for GIT I think I won't get any problem, since I'm pretty used to work with it.

Waiting for @kimhansen's answer about how to proceed.

**Comment by kimhansen** [comment]
The extra styles.xml files for particular languages are there on purpose and should not be removed. We have done our best to make the layouts as liquid as possible and independent on the language, but it is not always possible. They are basically there to correct layout issues that arise when long words or similar break the layout.
