### ISSUE TITLE
Publish Apps in Play Store?

### ISSUE THREAD

**Issue by lulebe** [Kwamecorp/Fairphone#9]
Hey, I quickly built the Launcher and wanted to make it available to all the Fairphone Fans who want to try the new Software before getting their device.
So I thought about uploading it for free to Google Play, but I couldn't find a license file to check if I'm allowed to do so.
Are you ok with that? I'd give all the credits to you and link this github project as well as fairphone's and kwamecorp's websites.

**Comment by Cathryne** [comment]
The PeaceOfMind-widget apparently already has been: https://github.com/Kwamecorp/Fairphone/pull/8
The author of that pull request can maybe answer your question.

Cheers!

**Comment by emanuil-tolev** [comment]
The Home widget does have one:
https://github.com/Kwamecorp/Fairphone/blob/master/FairphoneHome/LICENSE.txt?source=c seems to indicate an Apache 2 license.

I used to worry about this and to be fair, git repos should have a license (or they're under default copyright, which is very restrictive). On the other hand, licensing is a social construct, as is copyright law, which basically means that if people don't care enough to put a license, but they've published it on github, they _probably_ won't care if you take it. Fairphone is the customer in this case and they seem to want everything open-sourced so I wouldn't worry at all.

**Comment by lulebe** [comment]
Oh, thank you! They have the license inside the project directory for the homescreen as well. So I just had to check that out, it's apache2, so I guess they'll be fine with it. And of course I changed the package name from org.fairphone... to something else, so they can upload it themselves if they want to.

**Comment by kimhansen** [comment]
Hi guys, I added the Apache License to the root of the Fairphone project. It was only inside the FairphoneHome folder. You are free to publish apps on the Google Play store.
